# Generated by Django 3.1 on 2020-09-24 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poll',
            old_name='title',
            new_name='question',
        ),
        migrations.AlterField(
            model_name='poll',
            name='choice1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='poll',
            name='choice2',
            field=models.CharField(max_length=100),
        ),
    ]
