# Generated by Django 3.1 on 2020-09-24 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20200924_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='choice1_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='poll',
            name='choice2_count',
            field=models.IntegerField(default=0),
        ),
    ]
